# Generated by Django 5.1 on 2026-07-02 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_units', to=settings.AUTH_USER_MODEL)),
                ('lecturers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'lecturer'}, related_name='taught_units', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assignments.unit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10)),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('attached_by', models.ForeignKey(help_text='The rep who attached this class to the unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_offerings', to=settings.AUTH_USER_MODEL)),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_offerings', to='classes.class')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='assignments.unit')),
            ],
            options={
                'ordering': ['-attached_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/%Y/%m/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='groups.group')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assignment', 'group')},
            },
        ),
        migrations.CreateModel(
            name='GroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='assignments.assignment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='groups.group')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='assignments.unitoffering')),
            ],
            options={
                'unique_together': {('group', 'assignment')},
            },
        ),
    ]
