# Generated by Django 5.1 on 2026-08-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('ready_to_submit', 'Ready to Submit'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='pending', max_length=20),
        ),
    ]
