# Generated by Django 5.1 on 2026-08-12 05:28

import Groupwork.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_groupassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/%Y/%m/', validators=[Groupwork.validators.validate_upload]),
        ),
    ]
