# Generated by Django 5.1 on 2026-08-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Status Updated'), ('task_overdue', 'Task Overdue'), ('group_joined', 'Member Joined Group'), ('assignment_posted', 'New Assignment Posted'), ('submission_made', 'Submission Made'), ('group_assigned', 'Assignment Linked to Group'), ('ready_to_submit', 'All Tasks Done — Ready to Submit'), ('leadership_transferred', 'Leadership Transferred'), ('rep_added', 'Added as Class Representative')], max_length=30),
        ),
    ]
