# Generated by Django 5.1 on 2026-08-12 05:28

import Groupwork.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='task_evidence/%Y/%m/', validators=[Groupwork.validators.validate_upload]),
        ),
    ]
