# Generated by Django 5.1 on 2026-07-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'BBIT 3.2' — display label, not used for uniqueness", max_length=100)),
                ('program', models.CharField(help_text="e.g. 'BBIT'", max_length=100)),
                ('stage', models.CharField(choices=[('1.1', 'Year 1, Semester 1'), ('1.2', 'Year 1, Semester 2'), ('2.1', 'Year 2, Semester 1'), ('2.2', 'Year 2, Semester 2'), ('3.1', 'Year 3, Semester 1'), ('3.2', 'Year 3, Semester 2'), ('4.1', 'Year 4, Semester 1'), ('4.2', 'Year 4, Semester 2')], max_length=10)),
                ('cohort_year', models.PositiveIntegerField(help_text="The year this cohort first enrolled — disambiguates this year's 3.2 from next year's 3.2")),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-cohort_year', 'program', 'stage'],
            },
        ),
    ]
